name: DragonRun
version: ${version}
main: com.dragonrun.DragonRunPlugin
api-version: "1.21"
description: Hardcore roguelike - kill the dragon or die trying
author: DragonRunDev
website: https://github.com/dragonrun/dragon-run

load: STARTUP

permissions:
  dragonrun.admin:
    description: Admin commands
    default: op
  dragonrun.aura:
    description: Check aura
    default: true
  dragonrun.shop:
    description: Use shop
    default: true
  dragonrun.bet:
    description: Place bets
    default: true
  dragonrun.stats:
    description: View stats
    default: true
  dragonrun.live:
    description: View live player tracker
    default: true
  dragonrun.achievements:
    description: View achievements
    default: true

# Commands are registered programmatically using Paper's Brigadier API
